### ISSUE TITLE
Issue Loading The Plugin

### ISSUE THREAD

**Issue by OfficialLilKev** [BlockHorizons/ServerManager#3]
24.07 15:34:30 [Server] Server thread/CRITICAL ParseError: "syntax error, unexpected 'implememts' (T_STRING), expecting '{'" (EXCEPTION) in "/ServerManager-master/src/BlockHorizons/ServerManager/commands/BaseCommand" at line 11

please fix this

**Comment by Sandertv** [comment]
This plugin is nowhere near usable stage yet. Please hang on until it actually does something.

**Comment by OfficialLilKev** [comment]
when will it be thats the only issue
